eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765
spring:
  application:
    name: service-feign


# feign:
 # hystrix:
    #enabled : true


# 设置feign客户端超时时间
ribbon:
# 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
 ReadTimeout: 5000
# 建立连接后从服务器读取到可用资源所用的时间。
 ConnectTimeout: 5000
