eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765
spring:
  application:
    name: service-feign


# feign:
 # hystrix:
    #enabled : true

feign:
 client:
  config:
   default:
    connectTimeout: 5000
    readTimeout: 5000