spring:
  application:
    name: stock-service

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: roof
      url: jdbc:mysql://127.0.0.1:3306/stockservice?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC

  redis:
    # Redis数据库索引，默认为0
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 16379
    # Redis密码，默认为空
    password:
    # Redis连接池最大连接数(负值表示没有限制
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间
    timeout: 10000

server:
  port: 8883

# 事务协调者
tx-lcn:
  client:
   manager-address: 127.0.0.1:9999
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
