eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-hello:
      path: /api-hi/**
      serviceId: service-client-hi
    api-hi:
      path: /api-hello/**
      serviceId: service-client-hello

