server:
  port: 8769
spring:
  cloud:
    config:
      server:
        git:
          # git环境地址
          uri: https://gitee.com/Sirius_hly/respo.git
          # 搜索目录
          search-paths:
            - share
      # 读取分支
      label: master
  application:
    name: service-config-server







